import smtplib
from email.message import EmailMessage

def send_email(to_address, pdf_path, subject="Your AI Resume"):
    from_address = "your_email@gmail.com"
    password = "your_app_password"

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = from_address
    msg["To"] = to_address
    msg.set_content("Here is your resume generated by AI Resume Generator.")

    with open(pdf_path, "rb") as f:
        pdf_data = f.read()
        msg.add_attachment(pdf_data, maintype="application", subtype="pdf", filename=pdf_path)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(from_address, password)
        smtp.send_message(msg)
