# core/exporter.py

from fpdf import FPDF
from docx import Document
import uuid

class ResumePDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, "AI Resume Generator", ln=True, align="C")

def export_to_pdf(text: str, template: str = "tech") -> str:
    pdf = ResumePDF()
    pdf.add_page()

    # 设置不同风格样式
    if template == "tech":
        pdf.set_font("Courier", size=11)
        pdf.set_text_color(0, 0, 0)
    elif template == "business":
        pdf.set_font("Times", "B", 13)
        pdf.set_text_color(40, 40, 80)
    elif template == "academic":
        pdf.set_font("Helvetica", size=12)
        pdf.set_text_color(60, 60, 60)

    pdf.set_auto_page_break(auto=True, margin=15)

    for line in text.split("\n"):
        pdf.multi_cell(0, 10, line)

    # 商务风添加页脚
    if template == "business":
        pdf.set_y(-15)
        pdf.set_font("Arial", "I", 9)
        pdf.cell(0, 10, "Generated by AI Resume Generator", 0, 0, "C")

    filename = f"resume_{template}_{uuid.uuid4().hex[:6]}.pdf"
    pdf.output(filename)
    return filename

def export_to_docx(text: str) -> str:
    doc = Document()
    doc.add_heading("AI Enhanced Resume", level=1)

    for line in text.split("\n"):
        doc.add_paragraph(line)

    filename = f"resume_{uuid.uuid4().hex[:6]}.docx"
    doc.save(filename)
    return filename
